project_name: todox
builds:
  - id: todox
    main: ./cmd/todox
    binary: todox
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
archives:
  - id: archives
    builds: [todox]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
checksum:
  name_template: "checksums.txt"
