name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            archive: tar.gz
          - goos: linux
            goarch: arm64
            archive: tar.gz
          - goos: darwin
            goarch: amd64
            archive: tar.gz
          - goos: darwin
            goarch: arm64
            archive: tar.gz
          - goos: windows
            goarch: amd64
            archive: zip
          - goos: windows
            goarch: arm64
            archive: zip
    env:
      CGO_ENABLED: 0
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build binary
        run: |
          mkdir -p dist
          BIN_NAME="todox-${GOOS}-${GOARCH}"
          if [ "${GOOS}" = "windows" ]; then
            BIN_NAME="${BIN_NAME}.exe"
          fi
          go build -o "dist/${BIN_NAME}" ./cmd/todox

      - name: Package artifact
        shell: bash
        run: |
          cd dist
          BIN_NAME="todox-${GOOS}-${GOARCH}"
          if [ "${GOOS}" = "windows" ]; then
            BIN_FILE="${BIN_NAME}.exe"
            ARCHIVE_NAME="${BIN_NAME}.zip"
            zip -9 "${ARCHIVE_NAME}" "${BIN_FILE}"
            rm "${BIN_FILE}"
          else
            BIN_FILE="${BIN_NAME}"
            ARCHIVE_NAME="${BIN_NAME}.tar.gz"
            tar -czf "${ARCHIVE_NAME}" "${BIN_FILE}"
            rm "${BIN_FILE}"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: todox-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/todox-${{ matrix.goos }}-${{ matrix.goarch }}.*

  release:
    name: Publish release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: 'todox-*'
          path: dist
          merge-multiple: true

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
